/* DON'T EDIT THIS FILE. This is generated by 'scripts/update-lib-index.js' */
"use strict"

module.exports = {
    rules: {
        "no-deprecated-api": require("./rules/no-deprecated-api"),
    },
}
